name: CI/CD Pipeline

on:
  push:
    branches:
      - main

- name: Debug secrets
  run: |
    echo "DOCKERHUB_USERNAME set: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
    echo "DOCKERHUB_PASSWORD set: ${{ secrets.DOCKERHUB_PASSWORD != '' }}"

- name: Log in to DockerHub
  uses: docker/login-action@v3
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_PASSWORD }}

- name: Build, tag, and push image to DockerHub
  env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    IMAGE_NAME: my-image
  run: |
    docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .
    docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
